version: '2'
services:
  irpf:
    container_name: irpf
    image: caixote/irpf
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/ProgramasRFB:/home/irpf/ProgramasRFB
