version: '3.7'
services:
  irpf:
    container_name: irpf
    image: caixote/irpf
    build: .
    environment:
      - LANG=pt_BR.UTF-8
      - DISPLAY=${DISPLAY}
      - HOST_HOSTNAME=${HOSTNAME}
      - _JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on'
    shm_size: 2g
    volumes:
      - /dev/shm:/dev/shm
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro
      - /etc/machine-id:/etc/machine-id:ro
      # - ~/ProgramasRFB:/root/ProgramasRFB
